### ISSUE TITLE
Update to support MC 1.21.1

### ISSUE THREAD

**Issue by tim740** [uskyblock/uSkyBlock#58]
Currently, the plugin version:  3.1.0-SNAPSHOT doesn't fully enable and disables its self on MC 1.21.1
Using paper

**Comment by minoneer** [comment]
Also an issue with 1.21.3:

```
[14:59:51] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v3.1.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: NETHER_PORTAL isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.utils.util.ItemStackUtil.getItemType(ItemStackUtil.java:82) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.utils.util.ItemStackUtil.createItemRequirement(ItemStackUtil.java:38) ~[uSkyBlock.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createChallenge(ChallengeFactory.java:52) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.challenge.Rank.<init>(Rank.java:31) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createRankMap(ChallengeFactory.java:123) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:57) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:776) ~[uSkyBlock.jar:?]
	at uSkyBlock.jar/us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:227) ~[uSkyBlock.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:59:51] [Server thread/INFO]: [uSkyBlock] Disabling uSkyBlock v3.1.0-SNAPSHOT
```
